# Generated by Django 5.2.15 on 2026-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_member_aadhaar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyresource',
            name='half_day_hours',
            field=models.IntegerField(default=6),
        ),
    ]
