# Generated by Django 5.2.15 on 2026-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_propertyresource_half_day_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyresource',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
