# Generated by Django 5.2.14 on 2026-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_propertyresource_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedependency',
            name='dependency_type',
            field=models.CharField(choices=[('parent_child', 'Parent -> Child Dependency'), ('combination', 'Combination Dependency')], default='parent_child', max_length=20),
        ),
    ]
