# Generated by Django 5.2.14 on 2026-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_resourcedependency_dependency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproperty',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Default tax % applied to bookings', max_digits=5),
        ),
    ]
