# Generated by Django 5.2.15 on 2026-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_member_job_address_member_job_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='photo_permission',
            field=models.CharField(default='Everyone', max_length=100),
        ),
    ]
