# Generated by Django 5.2.15 on 2026-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_matrimonyprofile_photo_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreference',
            name='abroad_preference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='disability_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='drinking',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='family_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='family_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='family_values',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='horoscope_matching',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='manglik',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='photo_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='preferred_communities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='preferred_languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='profile_verified_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='recently_active_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='smoking',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='willing_to_relocate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
