# Generated by Django 5.2.15 on 2026-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreference',
            name='preferences_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
