# Generated by Django 5.2.15 on 2026-06-29 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_partnerpreference_preferences_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('billing_cycle', models.CharField(default='Monthly', max_length=50)),
                ('limit_type', models.CharField(max_length=100)),
                ('limit_value', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='color_theme',
            field=models.CharField(default='from-blue-600 to-indigo-700', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='community_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_email_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_sms_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='domain_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_period_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gst_percentage',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='half_yearly_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_best_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='lifetime_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_admin_users',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_api_calls',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_businesses',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_committee_members',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_communities',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_donations',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_email_credits',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_events',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_family_members',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_gallery_images',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_jobs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_matrimony_profiles',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_members',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_notifications',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_sms',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_staff_users',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storage_gb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_venues',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_whatsapp_credits',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='quarterly_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='white_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='member_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='modules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommunitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Trial', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('limits_override', models.JSONField(blank=True, default=dict)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.community')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.community')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(blank=True, default='', max_length=50)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('gst_invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='api.community')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('current_usage', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to='api.community')),
            ],
            options={
                'unique_together': {('community', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='PlanFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_reject', models.BooleanField(default=False)),
                ('can_assign', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.featuremaster')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='api.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
