# Generated by Django 5.2.15 on 2026-06-29 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_featuremaster_planaddon_subscriptionplan_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('module_code', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('route', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_sidebar_module', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('supports_subscription', models.BooleanField(default=False)),
                ('supports_permissions', models.BooleanField(default=False)),
                ('supports_usage_counter', models.BooleanField(default=False)),
                ('supports_analytics', models.BooleanField(default=False)),
                ('supports_audit_logs', models.BooleanField(default=False)),
                ('supports_notifications', models.BooleanField(default=False)),
                ('supports_export', models.BooleanField(default=False)),
                ('supports_import', models.BooleanField(default=False)),
                ('supports_search', models.BooleanField(default=False)),
                ('supports_api', models.BooleanField(default=False)),
                ('supports_mobile', models.BooleanField(default=False)),
                ('supports_dashboard_widgets', models.BooleanField(default=False)),
                ('supports_reports', models.BooleanField(default=False)),
                ('supports_approval_workflow', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_modules', to='api.applicationmodule')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModuleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationaction')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_actions', to='api.applicationmodule')),
            ],
            options={
                'unique_together': {('module', 'action')},
            },
        ),
    ]
