# Generated by Django 5.2.15 on 2026-06-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_memberpremiumaddon_memberpremiumplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planaddon')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.TextField(blank=True, default='')),
                ('gst', models.CharField(blank=True, default='', max_length=50)),
                ('pan', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('coupon', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='Paid', max_length=50)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_invoices', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('activated_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(max_length=100)),
                ('gateway', models.CharField(default='Razorpay', max_length=100)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.communityinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=0)),
                ('families', models.IntegerField(default=0)),
                ('businesses', models.IntegerField(default=0)),
                ('events', models.IntegerField(default=0)),
                ('jobs', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('gallery', models.IntegerField(default=0)),
                ('properties', models.IntegerField(default=0)),
                ('resources', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('api', models.IntegerField(default=0)),
                ('sms', models.IntegerField(default=0)),
                ('email', models.IntegerField(default=0)),
                ('whatsapp', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('analytics', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('purchased_addon', models.BooleanField(default=False)),
                ('usage_limit', models.IntegerField(default=0)),
                ('current_usage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='api.community')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicationmodule')),
            ],
            options={
                'unique_together': {('community', 'module')},
            },
        ),
    ]
