# Generated by Django 5.2.15 on 2026-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_memberpremiumreward_memberpremiumsupportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeatureRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('feature_name', models.CharField(max_length=200)),
                ('feature_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('icon', models.CharField(blank=True, default='star', max_length=100)),
                ('dependency', models.CharField(blank=True, default='', max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'verbose_name': 'Premium Feature Registry',
                'verbose_name_plural': 'Premium Feature Registries',
            },
        ),
    ]
