# Generated by Django 5.2.15 on 2026-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_premiumfeatureregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpremiumfeature',
            name='category',
            field=models.CharField(choices=[('matrimony', 'Matrimony'), ('messaging', 'Messaging'), ('business', 'Business'), ('jobs', 'Jobs'), ('events', 'Events'), ('property', 'Property Booking'), ('directory', 'Directory'), ('profile', 'Profile'), ('ai', 'AI Features'), ('marketplace', 'Marketplace'), ('support', 'Support'), ('donations', 'Donations'), ('ads', 'Advertisements'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
